module.exports = {
  purge: ["./src/{components,pages,styles}/**/*.{js,ts,jsx,tsx}"],
  prefix: "",
  important: false,
  separator: ":",
  darkMode: "media",
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
    },
    extend: {
      fontSize: {
        tiny: ".730rem",
      },
      colors: {
        transparent: "transparent",
        black: "#000",
        white: "#fff",
        background: {
          100: "#fff",
        },
        primary: {
          100: "#CBE7FE",
          200: "#98CCFD",
          300: "#64ABFB",
          400: "#055DF9",
          500: "#005FF3",
          600: "#0049D0",
          700: "#0036AE",
          800: "#00268C",
          900: "#001B74",
        },
        secondary: {
          100: "#CCFEF4",
          200: "#9BFDF1",
          300: "#68FBF5",
          400: "#FC5BB3",
          500: "#07D6F2",
          600: "#05A7D0",
          700: "#037EAE",
          800: "#025A8C",
          900: "#014174",
        },
        success: {
          100: "#E9FEE1",
          200: "#CEFDC3",
          300: "#ADFAA4",
          400: "#01EFAD",
          500: "#67EF72",
          600: "#4BCD61",
          700: "#33AC53",
          800: "#208A46",
          900: "#13723D",
        },
        warning: {
          100: "#FEF2D0",
          200: "#FDE2A1",
          300: "#FBCD72",
          400: "#F8B84E",
          500: "#F49716",
          600: "#D17810",
          700: "#AF5C0B",
          800: "#8D4407",
          900: "#753204",
        },
        danger: {
          100: "#FCE7DE",
          200: "#FACBBF",
          300: "#F1A59B",
          400: "#E3817F",
          500: "#D2565E",
          600: "#B43E51",
          700: "#972B45",
          800: "#791B3A",
          900: "#641034",
        },
        gray: {
          100: "#f7fafc",
          200: "#edf2f7",
          300: "#e2e8f0",
          400: "#F3F4F8",
          500: "#a0aec0",
          600: "#718096",
          700: "#4a5568",
          800: "#2d3748",
          900: "#1a202c",
        },
      },
      width: {
        fit: "fit-content",
      },
    },
  },
  variants: {
    extend: {
      accessibility: ["responsive", "focus"],
      alignContent: ["responsive"],
      alignItems: ["responsive"],
      alignSelf: ["responsive"],
      appearance: ["responsive"],
      backgroundAttachment: ["responsive"],
      backgroundColor: ["responsive", "hover", "focus", "group-hover"],
      backgroundImage: ["responsive", "hover"],
      backgroundPosition: ["responsive"],
      backgroundRepeat: ["responsive"],
      backgroundSize: ["responsive"],
      borderCollapse: ["responsive"],
      borderColor: ["responsive", "hover", "focus", "group-hover"],
      borderRadius: ["responsive"],
      borderStyle: ["responsive"],
      borderWidth: ["responsive"],
      boxShadow: ["responsive", "hover", "focus"],
      boxSizing: ["responsive"],
      cursor: ["responsive"],
      display: ["responsive"],
      fill: ["responsive"],
      flex: ["responsive"],
      flexDirection: ["responsive"],
      flexGrow: ["responsive"],
      flexShrink: ["responsive"],
      flexWrap: ["responsive"],
      float: ["responsive"],
      clear: ["responsive"],
      fontFamily: ["responsive"],
      fontSize: ["responsive"],
      fontSmoothing: ["responsive"],
      fontStyle: ["responsive"],
      fontWeight: ["responsive", "hover", "focus"],
      height: ["responsive"],
      inset: ["responsive"],
      justifyContent: ["responsive"],
      letterSpacing: ["responsive"],
      lineHeight: ["responsive"],
      listStylePosition: ["responsive"],
      listStyleType: ["responsive"],
      margin: ["responsive"],
      maxHeight: ["responsive"],
      maxWidth: ["responsive"],
      minHeight: ["responsive"],
      minWidth: ["responsive"],
      objectFit: ["responsive"],
      objectPosition: ["responsive"],
      opacity: ["responsive", "hover", "focus"],
      order: ["responsive"],
      outline: ["responsive", "focus"],
      overflow: ["responsive"],
      padding: ["responsive"],
      placeholderColor: ["responsive", "focus"],
      pointerEvents: ["responsive"],
      position: ["responsive"],
      resize: ["responsive"],
      stroke: ["responsive"],
      strokeWidth: ["responsive"],
      tableLayout: ["responsive"],
      textAlign: ["responsive"],
      textColor: ["responsive", "hover", "focus", "group-focus", "group-hover"],
      textDecoration: ["responsive", "hover", "focus"],
      textTransform: ["responsive"],
      userSelect: ["responsive"],
      verticalAlign: ["responsive"],
      visibility: ["responsive"],
      whitespace: ["responsive"],
      width: ["responsive"],
      wordBreak: ["responsive"],
      zIndex: ["responsive"],
      gap: ["responsive"],
      gridAutoFlow: ["responsive"],
      gridTemplateColumns: ["responsive"],
      gridColumn: ["responsive"],
      gridColumnStart: ["responsive"],
      gridColumnEnd: ["responsive"],
      gridTemplateRows: ["responsive"],
      gridRow: ["responsive"],
      gridRowStart: ["responsive"],
      gridRowEnd: ["responsive"],
      transform: ["responsive"],
      transformOrigin: ["responsive"],
      scale: ["responsive", "hover", "focus"],
      rotate: ["responsive", "hover", "focus"],
      translate: ["responsive", "hover", "focus"],
      skew: ["responsive", "hover", "focus"],
      transitionProperty: ["responsive"],
      transitionTimingFunction: ["responsive"],
      transitionDuration: ["responsive"],
    },
  },
  corePlugins: {},
  plugins: [],
};
